matrix:
    - language: node_js
      sudo: required
      dist: trusty
      node_js:
        - 6
      rvm:
        - 2.2.3
      cache:
        directories:
        - docs/vendor/bundle
        - node_modules
        - $HOME/.yarn-cache
      before_install:
        - cd opencti-frontend
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install:
        - yarn install
      script:
        - yarn build

    - language: node_js
      sudo: required
      dist: trusty
      node_js:
        - 6
      rvm:
        - 2.2.3
      cache:
        directories:
        - docs/vendor/bundle
        - node_modules
        - $HOME/.yarn-cache
      before_install:
        - cd opencti-graphql
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      install:
        - yarn install
      script:
        - yarn test

notifications:
  email: contact@luatix.org
