version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.6
    ports:
      - 48555:48555 
    volumes:
      - ./volumes/grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
    restart: always
  rabbitmq:
    image: rabbitmq
    restart: always
  worker:
    image: opencti/worker
    environment:
      - RUN_USER=root
      - OPENCTI_PORT=8080
    volumes:
      - "./config:/opt/opencti/shared_config:rw"
    depends_on:
      - opencti
    links:
      - opencti:opencti
    restart: always
  integration:
    image: opencti/integration
    environment:
      - RUN_USER=root
      - OPENCTI_PORT=8080
    volumes:
      - "./config:/opt/opencti/shared_config:rw"
    depends_on:
      - opencti
    links:
      - opencti:opencti
    restart: always    
  opencti:
    image: opencti/platform
    environment:
      - RUN_USER=root
      - APP__PORT=8080
      - APP__LOGS=./logs
      - APP__CONNECTORS=./integration/connectors
      - APP__SECRET=ChangeMe
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__HOSTNAME=elasticsearch
      - ELASTICSEARCH__PORT=9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
    ports:
      - "8080:8080"
    volumes:
      - "./config:/opt/opencti/shared_config:rw"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    links:
     - grakn:grakn
     - redis:redis
     - elasticsearch:elasticsearch
     - rabbitmq:rabbitmq
    restart: always
