version: 2.1

jobs:
  build:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - checkout
      - run: 
          working_directory: ~/opencti/opencti-front
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-front
          command: yarn build
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn build

  test:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn test

    deploy:
      working_directory: ~/opencti
      docker:
        - image: circleci/node:11-stretch
      steps:
        - run: mkdir deploy
        - run:
            working_directory: ~/opencti/deploy
            command: git clone 
workflows:
  opencti:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
