version: 2.1
jobs:
  build_opencti:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:9.9-stretch
    steps:
      - checkout
      - run: cd opencti-frontend
      - run: yarn install
      - run: yarn build
      - run: cd ../opencti-graphql
      - run: yarn install
      - run: yarn test
      - run: yarn build
workflows:
  opencti:
    jobs:
      - build_opencti
