version: 2.1

jobs:
  build:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - checkout
      - run: 
          working_directory: ~/opencti/opencti-front
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-front
          command: yarn build
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn build

  test:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn test

  deploy_community:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - run: sudo apt-get update -qq && apt install rsync
      - run: mkdir -p deploy/community
      - run:
          working_directory: ~/opencti/deploy/community
          command: git clone ssh://opencti-fiqid45E@opencti.io:/~/opencti-fiqid45E.git .
      - run:
          working_directory: ~/opencti/deploy/community
          command: rsync -auv --delete ~/opencti/opencti-graphql/public ./opencti-graphql/public
      - run:
          working_directory: ~/opencti/deploy/community
          command: rsync -auv --delete ~/opencti/opencti-graphql/dist ./opencti-graphql/dist
      - run:
          working_directory: ~/opencti/deploy/community
          command: git add * && git commit -a -m "[CircleCI-Workflow] Deploy new version" && git push origin master
workflows:
  opencti:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
