version: 2.1

jobs:
  build:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - checkout
      - run: 
          working_directory: ~/opencti/opencti-front
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-front
          command: yarn build
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: ls -la public/
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn install
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn build
      - persist_to_workspace:
          root: ~/
          paths:
            - opencti
  test:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - attach_workspace:
          at: ~/
      - run:
          working_directory: ~/opencti/opencti-graphql
          command: yarn test

  package_rolling:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H opencti.io >> ~/.ssh/known_hosts
      - run: git config --global user.email "ci@opencti.io" && git config --global user.name "OpenCTI CircleCI"
      - run: git remote add opencti ssh://git-OLOszi5F@opencti.io:/~/git-OLOszi5F.git && git push opencti master
      - run: mkdir release
      - run: cp -a opencti-graphql release/opencti
      - run: cp -a opencti-worker release/opencti/worker
      - run: cp -a opencti-clients release/opencti/clients
      - run: 
          working_directory: ~/opencti/release
          command: tar -zcvf "opencti-$(date '+%Y%m%d').tar.gz" opencti
      - run: 
          working_directory: ~/opencti/release
          command: scp "opencti-$(date '+%Y%m%d').tar.gz" git-OLOszi5F@opencti.io:/dns/io/opencti/releases/

  deploy_community:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H opencti.io >> ~/.ssh/known_hosts
      - run: sudo apt-get update -qq && sudo apt install rsync
      - run: mkdir deploy
      - run: git config --global user.email "ci@opencti.io" && git config --global user.name "OpenCTI CircleCI"
      - run:
          working_directory: ~/opencti/deploy
          command: git clone ssh://opencti-fiqid45E@opencti.io:/~/opencti-fiqid45E.git .
      - run:
          working_directory: ~/opencti/deploy
          command: git remote add ci ~/opencti && git pull --no-edit ci master
      - run:
          working_directory: ~/opencti/deploy
          command: rsync -auv --delete ~/opencti/opencti-graphql/public ./opencti-graphql/public
      - run:
          working_directory: ~/opencti/deploy
          command: rsync -auv --delete ~/opencti/opencti-graphql/dist ./opencti-graphql/dist
      - run:
          working_directory: ~/opencti/deploy
          command: git add --all && git commit -a -m "[CircleCI-Workflow] Deploy new version" && git push origin master

  deploy_demo:
    working_directory: ~/opencti
    docker:
      - image: circleci/node:11-stretch
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: ssh-keyscan -H opencti.io >> ~/.ssh/known_hosts    
      - run: sudo apt-get update -qq && sudo apt install rsync
      - run: mkdir -p deploy
      - run: git config --global user.email "ci@opencti.io" && git config --global user.name "OpenCTI CircleCI"
      - run:
          working_directory: ~/opencti/deploy
          command: git clone ssh://opencti-b0gY5UHe@opencti.io:/~/opencti-b0gY5UHe.git .
      - run:
          working_directory: ~/opencti/deploy
          command: git remote add ci ~/opencti && git pull --no-edit ci master          
      - run:
          working_directory: ~/opencti/deploy
          command: rsync -auv --delete ~/opencti/opencti-graphql/public ./opencti-graphql/public
      - run:
          working_directory: ~/opencti/deploy
          command: rsync -auv --delete ~/opencti/opencti-graphql/dist ./opencti-graphql/dist
      - run:
          working_directory: ~/opencti/deploy
          command: git add --all && git commit -a -m "[CircleCI-Workflow] Deploy new version" && git push origin master

workflows:
  opencti:
    jobs:
      - build
      - test:
          requires:
            - build
      - package_rolling:
          requires:
            - build
            - test
      - deploy_community:
          requires:
            - build
            - test
      - deploy_demo:
          requires:
            - build
            - test