version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.0
    restart: always
  redis:
    image: redis
    restart: always
  rabbitmq:
    image: rabbitmq
    restart: always  
  opencti:
    image: luatix/opencti
    build:
      context: .
    environment:
      - RUN_USER=root
      - APP_PORT=4000
      - APP_LOGS=./logs
      - APP_SECRET=ChangeMe
      - APP_REACTIVE=true
      - APP_COOKIE_SECURE=false
      - GRAKN_HOSTNAME=grakn
      - GRAKN_PORT=48555
      - GRAKN_TIMEOUT=30000
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    ports:
      - "4000:4000"
    depends_on:
      - grakn
      - redis
      - rabbitmq
    links:
     - grakn:grakn
     - redis:redis
     - rabbitmq:rabbitmq
    restart: always
